import { FC } from "react";
import styles from "./styles.module.scss";

export const TermsPage: FC = () => {
    return (
        <div className={styles.root}>
            <p className={styles.label}>Rent terms place here.</p>
            <p className={styles.text}>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sapien pellentesque habitant morbi tristique senectus. Ornare massa eget egestas purus viverra accumsan. Vitae tempus quam pellentesque nec nam aliquam sem. Vulputate dignissim suspendisse in est ante in nibh. Non pulvinar neque laoreet suspendisse interdum. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. Tellus cras adipiscing enim eu turpis egestas. Pulvinar elementum integer enim neque. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam. Arcu vitae elementum curabitur vitae nunc sed velit. Amet aliquam id diam maecenas ultricies mi eget. Aliquet sagittis id consectetur purus ut faucibus. Habitasse platea dictumst vestibulum rhoncus est. Elit at imperdiet dui accumsan sit.
            </p>
            <p className={styles.text}>
                Arcu non sodales neque sodales ut etiam sit amet. Commodo nulla facilisi nullam vehicula ipsum. A pellentesque sit amet porttitor eget. Ut venenatis tellus in metus. Et pharetra pharetra massa massa. Id faucibus nisl tincidunt eget nullam. Nulla at volutpat diam ut venenatis tellus in. Eget sit amet tellus cras adipiscing. Scelerisque fermentum dui faucibus in ornare quam viverra. Lacus vel facilisis volutpat est velit egestas. Eget magna fermentum iaculis eu non diam phasellus vestibulum lorem. Diam ut venenatis tellus in. Justo nec ultrices dui sapien eget mi. Vel pharetra vel turpis nunc eget lorem dolor sed. Vel turpis nunc eget lorem dolor.
            </p>
            <p className={styles.text}>
                At volutpat diam ut venenatis tellus in metus. Est ante in nibh mauris cursus mattis molestie. Praesent semper feugiat nibh sed. Ac felis donec et odio pellentesque diam. Fermentum et sollicitudin ac orci phasellus egestas tellus. Varius duis at consectetur lorem donec massa sapien faucibus. Fusce id velit ut tortor pretium viverra suspendisse. Congue quisque egestas diam in arcu cursus euismod. Laoreet non curabitur gravida arcu ac tortor dignissim convallis. Praesent tristique magna sit amet purus gravida quis. Viverra maecenas accumsan lacus vel facilisis volutpat est. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus.
            </p>
            <p className={styles.text}>
                Arcu risus quis varius quam quisque id diam. Pellentesque eu tincidunt tortor aliquam. Orci a scelerisque purus semper eget duis at tellus. Odio ut enim blandit volutpat maecenas. Ut diam quam nulla porttitor massa id neque. Quis blandit turpis cursus in hac habitasse. Lacus suspendisse faucibus interdum posuere lorem. Viverra aliquet eget sit amet tellus. Eget mi proin sed libero enim. Accumsan in nisl nisi scelerisque eu ultrices vitae. Convallis a cras semper auctor neque vitae tempus quam. Ac orci phasellus egestas tellus rutrum. Nunc lobortis mattis aliquam faucibus purus in massa. Ut pharetra sit amet aliquam. Non tellus orci ac auctor augue. Penatibus et magnis dis parturient montes nascetur ridiculus.
            </p>
            <p className={styles.text}>
                Tortor id aliquet lectus proin. Mi bibendum neque egestas congue quisque egestas diam. Quam nulla porttitor massa id. Amet consectetur adipiscing elit pellentesque habitant morbi tristique. Iaculis eu non diam phasellus vestibulum lorem sed risus ultricies. Urna neque viverra justo nec ultrices. Morbi tincidunt augue interdum velit euismod in pellentesque. Magna fermentum iaculis eu non diam phasellus vestibulum lorem. Etiam erat velit scelerisque in. Amet purus gravida quis blandit.
            </p>
            <p className={styles.text}>
                Volutpat sed cras ornare arcu dui. Sem fringilla ut morbi tincidunt augue interdum velit euismod. Urna et pharetra pharetra massa. Sed vulputate odio ut enim blandit volutpat maecenas. Lobortis mattis aliquam faucibus purus in massa. Aliquet eget sit amet tellus cras adipiscing. Eget velit aliquet sagittis id consectetur purus ut faucibus pulvinar. Diam volutpat commodo sed egestas egestas fringilla. Nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Fermentum dui faucibus in ornare quam viverra orci. Sagittis purus sit amet volutpat consequat mauris nunc congue. Magna ac placerat vestibulum lectus mauris ultrices eros. Id diam vel quam elementum pulvinar etiam. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Commodo elit at imperdiet dui accumsan sit amet nulla. Nec ullamcorper sit amet risus nullam eget felis. Tincidunt dui ut ornare lectus sit amet est placerat in. Ultrices dui sapien eget mi proin sed libero enim. Lorem ipsum dolor sit amet consectetur. Leo in vitae turpis massa sed elementum tempus egestas.
            </p>
            <p className={styles.text}>
                Eget mauris pharetra et ultrices neque ornare aenean euismod elementum. Faucibus nisl tincidunt eget nullam non nisi. Nulla facilisi morbi tempus iaculis. Nulla malesuada pellentesque elit eget gravida. Nam at lectus urna duis convallis convallis tellus. Posuere ac ut consequat semper viverra nam. Elementum eu facilisis sed odio morbi quis. Posuere ac ut consequat semper. Enim sit amet venenatis urna cursus eget nunc scelerisque viverra. Nibh cras pulvinar mattis nunc sed blandit libero volutpat sed. Libero id faucibus nisl tincidunt eget nullam non nisi. Maecenas sed enim ut sem viverra aliquet eget. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Blandit libero volutpat sed cras ornare arcu dui. Faucibus in ornare quam viverra orci sagittis eu volutpat odio. In pellentesque massa placerat duis ultricies lacus. Donec ultrices tincidunt arcu non.
            </p>
            <p className={styles.text}>
                Adipiscing elit pellentesque habitant morbi tristique senectus et. Ante in nibh mauris cursus mattis molestie. Sapien pellentesque habitant morbi tristique senectus et netus et. Magnis dis parturient montes nascetur ridiculus mus mauris vitae ultricies. Lacinia quis vel eros donec ac odio tempor. Auctor neque vitae tempus quam pellentesque nec nam aliquam sem. Consectetur lorem donec massa sapien. Tortor id aliquet lectus proin nibh. Neque vitae tempus quam pellentesque nec nam aliquam. Nec tincidunt praesent semper feugiat. Lorem donec massa sapien faucibus et molestie ac. Nunc sed velit dignissim sodales. Ut tortor pretium viverra suspendisse potenti nullam ac. At imperdiet dui accumsan sit. Morbi non arcu risus quis varius quam. Ante in nibh mauris cursus mattis molestie a iaculis at.
            </p>
            <p className={styles.text}>
                Magna etiam tempor orci eu lobortis. Commodo sed egestas egestas fringilla phasellus. Lacus vestibulum sed arcu non odio euismod lacinia. Placerat vestibulum lectus mauris ultrices eros in. Lacus laoreet non curabitur gravida arcu. Tellus integer feugiat scelerisque varius morbi enim nunc faucibus a. Euismod quis viverra nibh cras pulvinar mattis. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc. Purus semper eget duis at. Quis risus sed vulputate odio ut enim blandit volutpat maecenas. Praesent tristique magna sit amet purus. Vitae nunc sed velit dignissim sodales ut eu sem integer. Diam maecenas sed enim ut. In arcu cursus euismod quis viverra nibh cras pulvinar mattis. Feugiat nibh sed pulvinar proin gravida hendrerit. At volutpat diam ut venenatis tellus. Sociis natoque penatibus et magnis dis parturient. Sollicitudin ac orci phasellus egestas tellus rutrum tellus pellentesque. Lacus vestibulum sed arcu non odio euismod. Dolor magna eget est lorem.
            </p>
            <p className={styles.text}>
                Magna sit amet purus gravida quis. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Eget lorem dolor sed viverra ipsum nunc aliquet bibendum. Diam quam nulla porttitor massa id. Non tellus orci ac auctor augue. Amet consectetur adipiscing elit ut aliquam. Mauris cursus mattis molestie a iaculis. Dapibus ultrices in iaculis nunc sed. Leo vel fringilla est ullamcorper eget nulla. Orci dapibus ultrices in iaculis nunc sed augue. Nulla facilisi etiam dignissim diam quis enim lobortis scelerisque. Ipsum faucibus vitae aliquet nec ullamcorper sit amet.
            </p>
        </div >
    );
};